kind: PersistentVolume
apiVersion: v1
metadata:
  name: map-data-volume
  labels:
    type: local
spec:
  storageClassName: map-data 
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/map"